### ISSUE TITLE
Error importing from Jira: "invalid issue description"

### ISSUE THREAD

**Issue by tomredman** [linear/linear-import#54]
Got an error on this issue, seems there's some formatting in the description that the importer doesn't like?

```
Error occurred while importing:

{
  "errors": [
    {
      "message": "invalid issue description",
      "path": [
        "issueCreate"
      ],
      "locations": [
        {
          "line": 12,
          "column": 13
        }
      ],
      "extensions": {
        "type": "invalid input",
        "userError": true,
        "userPresentableMessage": {}
      }
    }
  ],
  "data": null
}
ClientError: invalid issue description: {"response":{"errors":[{"message":"invalid issue description","path":["issueCreate"],"locations":[{"line":12,"column":13}],"extensions":{"type":"invalid input","userError":true,"userPresentableMessage":{}}}],"data":null,"status":200},"request":{"query":"\n          mutation createIssue(\n              $teamId: String!,\n              $projectId: String,\n              $title: String!,\n              $description: String,\n              $priority: Int,\n              $labelIds: [String!]\n              $stateId: String\n              $assigneeId: String\n            ) {\n            issueCreate(input: {\n                                teamId: $teamId,\n                                projectId: $projectId,\n                                title: $title,\n                                description: $description,\n                                priority: $priority,\n                                labelIds: $labelIds\n                                stateId: $stateId\n                                assigneeId: $assigneeId\n                              }) {\n              success\n            }\n          }\n        ","variables":{"teamId":"33cbb185-544d-44c8-b033-b0d7324e8bc0","title":"Avatars are often missing - need to store our own copy as FB URLs expire","description":"![](Screen Shot 2020-10-29 at 12.47.29 PM.png|width=449,height=520)\n\n[View original issue in Jira](https://buffer.atlassian.net/browse/AT-732)","priority":0,"labelIds":["ef86c3e2-b03b-413d-b975-262aacfd968a"]}}}
    at /Users/titan/.config/yarn/global/node_modules/@linear/import/dist/import.cjs.development.js:727:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: { errors: [ [Object] ], data: null, status: 200 },
  request: {
    query: '\n' +
      '          mutation createIssue(\n' +
      '              $teamId: String!,\n' +
      '              $projectId: String,\n' +
      '              $title: String!,\n' +
      '              $description: String,\n' +
      '              $priority: Int,\n' +
      '              $labelIds: [String!]\n' +
      '              $stateId: String\n' +
      '              $assigneeId: String\n' +
      '            ) {\n' +
      '            issueCreate(input: {\n' +
      '                                teamId: $teamId,\n' +
      '                                projectId: $projectId,\n' +
      '                                title: $title,\n' +
      '                                description: $description,\n' +
      '                                priority: $priority,\n' +
      '                                labelIds: $labelIds\n' +
      '                                stateId: $stateId\n' +
      '                                assigneeId: $assigneeId\n' +
      '                              }) {\n' +
      '              success\n' +
      '            }\n' +
      '          }\n' +
      '        ',
    variables: {
      teamId: '33cbb185-544d-44c8-b033-b0d7324e8bc0',
      projectId: undefined,
      title: 'Avatars are often missing - need to store our own copy as FB URLs expire',
      description: '![](Screen Shot 2020-10-29 at 12.47.29 PM.png|width=449,height=520)\n' +
        '\n' +
        '[View original issue in Jira](https://buffer.atlassian.net/browse/AT-732)',
      priority: 0,
      labelIds: [Array],
      stateId: undefined,
      assigneeId: undefined
    }
  }
}
```

**Comment by rlargman** [comment]
@tomredman Are you still seeing this issue? I'm not able to reproduce the failure.

**Comment by tomredman** [comment]
Cannot retest –– will reopen if I run into it again!
