### ISSUE TITLE
Github import fails

### ISSUE THREAD

**Issue by xarg** [linear/linear-import#55]
Once I enter `? From which repo do you want to import issues from (e.g. "facebook/react")` I get this error message:

```
TypeError: Cannot read property 'id' of null
    at /Users/a/Projects/linear-import/dist/import.cjs.development.js:1140:39
    at Array.filter (<anonymous>)
    at _temp3 (/Users/a/Projects/linear-import/dist/import.cjs.development.js:1139:69)
    at o (/Users/a/Projects/linear-import/dist/import.cjs.development.js:33:39)
    at _settle (/Users/a/Projects/linear-import/dist/import.cjs.development.js:70:4)
    at _resumeAfterBody (/Users/a/Projects/linear-import/dist/import.cjs.development.js:219:5)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by rlargman** [comment]
@xarg is this issue still happening? Can you give me more details about your input?

**Comment by xarg** [comment]
No, I used the main branch and it worked.
